local_costmap:
  local_costmap:
    ros__parameters:
      always_send_full_costmap: True
      global_frame: odom
      height: 3
      publish_frequency: 2.0
      resolution: 0.05
      robot_base_frame: base_link
      robot_radius: 0.1
      rolling_window: true
      update_frequency: 5.0
      use_sim_time: false
      width: 3
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.1

global_costmap:
  global_costmap:
    ros__parameters:
      always_send_full_costmap: True
      global_frame: map
      publish_frequency: 1.0
      resolution: 0.05
      robot_base_frame: base_link
      robot_radius: 0.1
      track_unknown_space: true
      update_frequency: 1.0
      use_sim_time: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.1

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.5  # s
    current_goal_checker: "goal_checker"
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 60.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: false
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      allow_reversing: true
      approach_velocity_scaling_dist: 0.3  # m
      curvature_lookahead_dist: 0.5  # m
      desired_linear_vel: 0.2  # m/s
      lookahead_dist: 0.6  # m
      lookahead_time: 1.5  # s
      max_allowed_time_to_collision_up_to_carrot: 1.0  # s
      max_angular_accel: 1.0  # rad/s
      min_approach_linear_velocity: 0.05  # m/s
      transform_tolerance: 0.1  # s
      use_collision_detection: false
      use_cost_regulated_linear_velocity_scaling: false
      use_fixed_curvature_lookahead: false
      use_regulated_linear_velocity_scaling: false
      use_rotate_to_heading: false
      use_velocity_scaled_lookahead_dist: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      allow_primitive_interpolation: false
      allow_unknown: true                 # allow traveling in unknown space
      analytic_expansion_max_length: 3.0  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
      angle_quantization_bins: 16         # Number of angle bins for search
      cache_obstacle_heuristic: false
      change_penalty: 0.0                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      cost_penalty: 2.0                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      debug_visualizations: false
      downsample_costmap: false           # whether or not to downsample the map
      downsample_obstacle_heuristic: true
      lookup_table_size: 3.75             # Size of the dubin/reeds-sheep distance window to cache, in meters.
      max_iterations: 10000               # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000    # Maximum number of iterations after within tolerances to continue to try to find exact solution
      max_planning_time: 5.0              # max time in s for planner to plan, smooth
      minimum_turning_radius: 0.5         # minimum turning radius in m of path / vehicle
      motion_model_for_search: "REEDS_SHEPP" # Hybrid-A* Dubin, Redds-Shepp
      non_straight_penalty: 1.2           # Penalty to apply if motion is non-straight, must be => 1
      retrospective_penalty: 0.015
      reverse_penalty: 2.0                # Penalty to apply if motion is reversing, must be => 1
      smooth_path: false
      tolerance: 0.5                      # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
      use_quadratic_cost_penalty: false

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 5.0
    behavior_plugins: ["backup", "drive_on_heading", "wait", "assisted_teleop"]
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: false
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 1.0

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 200
    default_nav_through_poses_bt_xml: /home/pi/rcar/install/share/rumi_nav/config/through_poses_bt.xml
    default_nav_to_pose_bt_xml: /home/pi/rcar/install/share/rumi_nav/config/to_pose_bt.xml
    plugin_lib_names:
      - nav2_assisted_teleop_action_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_back_up_action_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_controller_selector_bt_node
      - nav2_distance_controller_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_is_battery_charging_condition_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_path_longer_on_approach_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_planner_selector_bt_node
      - nav2_rate_controller_bt_node
      - nav2_recovery_node_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_single_trigger_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_speed_controller_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_wait_cancel_bt_node