services:
  main:
    extends:
      file: raspi_cross_ros2/docker-compose.yml
      service: main
    volumes:
      - ..:/home/pi/rcar/src
    working_dir: /home/pi/rcar
    entrypoint: /home/pi/rcar/src/RumiCarRos/docker/entrypoint
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
