services:
  main:
    image: raspi_cross_ros2
    build: raspi_cross_ros2
    volumes:
      - ~/raspi:/raspi
      - ~/raspi/usr/lib/gcc:/cross/lib/gcc
      - ~/ros_humble/install:/home/pi/ros_humble/install
      - ~/rcar/src:/home/pi/rcar/src
    working_dir: /home/pi/rcar
    entrypoint: /home/pi/rcar/src/RumiCarRos/docker/entrypoint
    command: bash
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
