services:
  main:
    image: raspi_cross_ros2
    volumes:
      - ~/raspi:/raspi
      - ~/raspi/usr/lib/gcc:/cross/lib/gcc
      - ~/ros_humble/install:/home/pi/ros_humble/install
      - ../..:/home/pi/rcar
    entrypoint: bash
    working_dir: /home/pi/rcar
