/**:
  ros__parameters:
    battery_led_pins: [ 5, 6, 16, 20, 21 ]
    battery_led_voltages: [ 3.2, 3.4, 3.6, 3.8 ]
    drive_gpios: [ 17, 27, 26, 22 ]
    drive_pwms: [ 0 ]
    drive_pwm_frequency: 36
