/**:
  ros__parameters:
    walk:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: cmd_vel
      deadman_buttons: [4]
      axis_mappings:
        header-frame_id:
          value: 'joy'
        twist-linear-x:
          axis: 1
          scale: 1.0
          offset: 0
        twist-angular-z:
          axis: 2
          scale: 0.45
          offset: 0
