/**:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 0.4
    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 0.45

    enable_button: 6  # Left trigger button
    enable_turbo_button: 7  # Right trigger button
